"""Markdown output formatter.

This module provides Markdown formatting for profiling results,
generating well-structured Markdown documents suitable for
documentation or README files.
"""

from __future__ import annotations

from typing import Any

from data_profiler.models.profile import FileProfile, DatasetProfile
from data_profiler.models.grouping import GroupingResult
from data_profiler.models.relationships import RelationshipGraph
from data_profiler.output.base import BaseFormatter


def _format_bytes(size: int) -> str:
    """Format bytes as human-readable string.

    Args:
        size: Size in bytes.

    Returns:
        Human-readable size string.
    """
    for unit in ["B", "KB", "MB", "GB", "TB"]:
        if abs(size) < 1024.0:
            return f"{size:,.1f} {unit}"
        size /= 1024.0  # type: ignore
    return f"{size:,.1f} PB"


def _format_number(value: Any) -> str:
    """Format a number for display.

    Args:
        value: Number to format.

    Returns:
        Formatted string.
    """
    if value is None:
        return "-"
    if isinstance(value, float):
        if abs(value) >= 1000:
            return f"{value:,.2f}"
        return f"{value:.4f}"
    if isinstance(value, int):
        return f"{value:,}"
    return str(value)


def _format_ratio(value: float | None) -> str:
    """Format a ratio as percentage.

    Args:
        value: Ratio between 0 and 1.

    Returns:
        Formatted percentage string.
    """
    if value is None:
        return "-"
    return f"{value * 100:.1f}%"


class MarkdownFormatter(BaseFormatter):
    """Formatter for Markdown output.

    Generates well-formatted Markdown documents with tables,
    headers, and proper structure.
    """

    def __init__(self, include_toc: bool = False) -> None:
        """Initialize Markdown formatter.

        Args:
            include_toc: Include table of contents.
        """
        self.include_toc = include_toc

    def format_file_profile(self, profile: FileProfile) -> str:
        """Format file profile as Markdown.

        Args:
            profile: FileProfile to format.

        Returns:
            Markdown string.
        """
        lines: list[str] = []

        # Header
        lines.append(f"# File Profile: {profile.file_path.name}")
        lines.append("")

        # Table of contents
        if self.include_toc:
            lines.append("## Table of Contents")
            lines.append("")
            lines.append("- [Summary](#summary)")
            lines.append("- [Column Statistics](#column-statistics)")
            if profile.warnings:
                lines.append("- [Warnings](#warnings)")
            lines.append("")

        # Summary section
        lines.append("## Summary")
        lines.append("")
        lines.append("| Property | Value |")
        lines.append("|----------|-------|")
        lines.append(f"| **File** | `{profile.file_path}` |")
        lines.append(f"| **Format** | {profile.file_format.upper()} |")
        lines.append(f"| **Size** | {_format_bytes(profile.file_size_bytes)} |")
        lines.append(f"| **Rows** | {profile.row_count:,} |")
        lines.append(f"| **Columns** | {profile.column_count} |")
        lines.append(f"| **Profiled At** | {profile.profiled_at.strftime('%Y-%m-%d %H:%M:%S')} |")
        lines.append(f"| **Duration** | {profile.duration_seconds:.2f}s |")
        lines.append("")

        # Column statistics
        lines.append("## Column Statistics")
        lines.append("")
        lines.append("| Column | Type | Count | Nulls | Null % | Unique | Unique % | Min | Max | Mean |")
        lines.append("|--------|------|------:|------:|-------:|-------:|--------:|----:|----:|-----:|")

        for col in profile.columns:
            lines.append(
                f"| **{col.name}** | {col.dtype.value} | "
                f"{col.count:,} | {col.null_count:,} | {_format_ratio(col.null_ratio)} | "
                f"{col.unique_count:,} | {_format_ratio(col.unique_ratio)} | "
                f"{_format_number(col.min_value)} | {_format_number(col.max_value)} | "
                f"{_format_number(col.mean)} |"
            )
        lines.append("")

        # Warnings
        if profile.warnings:
            lines.append("## Warnings")
            lines.append("")
            for warning in profile.warnings:
                lines.append(f"- {warning}")
            lines.append("")

        # Footer
        lines.append("---")
        lines.append("")
        lines.append("*Generated by data-profiler*")

        return "\n".join(lines)

    def format_dataset_profile(self, profile: DatasetProfile) -> str:
        """Format dataset profile as Markdown.

        Args:
            profile: DatasetProfile to format.

        Returns:
            Markdown string.
        """
        lines: list[str] = []

        # Header
        lines.append(f"# Dataset Profile: {profile.name}")
        lines.append("")

        # Table of contents
        if self.include_toc:
            lines.append("## Table of Contents")
            lines.append("")
            lines.append("- [Summary](#summary)")
            lines.append("- [Files](#files)")
            if profile.schema_drift_details:
                lines.append("- [Schema Drift](#schema-drift)")
            lines.append("")

        # Summary section
        lines.append("## Summary")
        lines.append("")
        lines.append("| Property | Value |")
        lines.append("|----------|-------|")
        lines.append(f"| **Files** | {profile.file_count} |")
        lines.append(f"| **Total Rows** | {profile.total_rows:,} |")
        lines.append(f"| **Total Size** | {_format_bytes(profile.total_size_bytes)} |")
        lines.append(f"| **Schema Consistent** | {'Yes' if profile.schema_consistent else 'No'} |")
        lines.append(f"| **Profiled At** | {profile.profiled_at.strftime('%Y-%m-%d %H:%M:%S')} |")
        lines.append("")

        # Files table
        lines.append("## Files")
        lines.append("")
        lines.append("| File | Format | Size | Rows | Columns | Duration |")
        lines.append("|------|--------|-----:|-----:|--------:|---------:|")

        for fp in profile.files:
            lines.append(
                f"| {fp.file_path.name} | {fp.file_format.upper()} | "
                f"{_format_bytes(fp.file_size_bytes)} | {fp.row_count:,} | "
                f"{fp.column_count} | {fp.duration_seconds:.2f}s |"
            )
        lines.append("")

        # Schema drift
        if profile.schema_drift_details:
            lines.append("## Schema Drift")
            lines.append("")
            lines.append("> **Warning:** Schema inconsistencies detected across files.")
            lines.append("")
            for detail in profile.schema_drift_details:
                lines.append(f"- {detail}")
            lines.append("")

        # Footer
        lines.append("---")
        lines.append("")
        lines.append("*Generated by data-profiler*")

        return "\n".join(lines)

    def format_grouping_result(self, result: GroupingResult) -> str:
        """Format grouping result as Markdown.

        Args:
            result: GroupingResult to format.

        Returns:
            Markdown string.
        """
        lines: list[str] = []

        # Header
        lines.append("# Grouping Result")
        lines.append("")

        # Summary
        lines.append("## Summary")
        lines.append("")
        lines.append("| Property | Value |")
        lines.append("|----------|-------|")
        lines.append(f"| **Group By** | {', '.join(result.columns)} |")
        lines.append(f"| **Total Rows** | {result.total_rows:,} |")
        lines.append(f"| **Groups** | {result.group_count} |")
        lines.append("")

        if result.skipped:
            lines.append("> **Warning:** " + (result.warning or "Grouping was skipped"))
            lines.append("")
            lines.append("---")
            lines.append("")
            lines.append("*Generated by data-profiler*")
            return "\n".join(lines)

        # Groups table
        lines.append("## Group Counts")
        lines.append("")

        # Build header
        header = "| " + " | ".join(result.columns) + " | Count | % of Total |"
        lines.append(header)

        # Build separator
        sep_parts = ["|"]
        for _ in result.columns:
            sep_parts.append("------|")
        sep_parts.append("-----:|")
        sep_parts.append("----------:|")
        lines.append("".join(sep_parts))

        # Build rows
        for group in result.groups:
            row_parts = ["|"]
            for col in result.columns:
                val = group.key.get(col)
                row_parts.append(f" {val if val is not None else '(null)'} |")

            pct = (group.row_count / result.total_rows * 100) if result.total_rows > 0 else 0
            row_parts.append(f" {group.row_count:,} |")
            row_parts.append(f" {pct:.1f}% |")
            lines.append("".join(row_parts))

        lines.append("")

        # Footer
        lines.append("---")
        lines.append("")
        lines.append("*Generated by data-profiler*")

        return "\n".join(lines)

    def format_relationship_graph(self, graph: RelationshipGraph) -> str:
        """Format relationship graph as Markdown.

        Args:
            graph: RelationshipGraph to format.

        Returns:
            Markdown string.
        """
        lines: list[str] = []

        # Header
        lines.append("# Relationship Discovery")
        lines.append("")

        # Summary
        lines.append("## Summary")
        lines.append("")
        lines.append("| Property | Value |")
        lines.append("|----------|-------|")
        lines.append(f"| **Entities** | {len(graph.entities)} |")
        lines.append(f"| **Relationships** | {len(graph.relationships)} |")
        lines.append("")

        # Entities
        if graph.entities:
            lines.append("## Entities")
            lines.append("")
            lines.append("| Entity | File | Primary Key(s) | Attributes |")
            lines.append("|--------|------|----------------|------------|")

            for entity in graph.entities:
                pk_cols = ", ".join(entity.primary_key_columns) if entity.primary_key_columns else "-"
                lines.append(
                    f"| **{entity.name}** | {entity.file_path.name} | "
                    f"{pk_cols} | {len(entity.attribute_columns)} columns |"
                )
            lines.append("")

        # Relationships
        if graph.relationships:
            lines.append("## Relationships")
            lines.append("")
            lines.append("| Parent | Parent Column | Child | Child Column | Type | Confidence | Source |")
            lines.append("|--------|---------------|-------|--------------|------|------------|--------|")

            for rel in graph.relationships:
                lines.append(
                    f"| **{rel.parent_file.stem}** | {rel.parent_column} | "
                    f"**{rel.child_file.stem}** | {rel.child_column} | "
                    f"{rel.relationship_type.value.replace('_', ' ').title()} | "
                    f"{rel.confidence:.0%} | {'Hint' if rel.is_hint else 'Detected'} |"
                )
            lines.append("")

            # Mermaid diagram
            lines.append("## Entity-Relationship Diagram")
            lines.append("")
            lines.append("```mermaid")
            lines.append(graph.to_mermaid())
            lines.append("```")
            lines.append("")

        # Footer
        lines.append("---")
        lines.append("")
        lines.append("*Generated by data-profiler*")

        return "\n".join(lines)
